
server:
  port : 8090
taco:
  orders:
    pageSize: 10

spring:
  thymeleaf:
    cache : false
  datasource:
    generate-unique-name : false
    name : tacocloud
  jpa:
    defer-datasource-initialization: false

    hibernate:
      ddl-auto: create-drop

